LaborReport/Models/ErrorViewModel.cs
using System;

namespace LaborReport.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LaborReport/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LaborReport.Models;

namespace LaborReport.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LaborReport/Controllers/InOutsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ExcelDataReader;
using LaborReport.Datas;
using LaborReport.Datas.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace LaborReport.Controllers
{
    public class InOutsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InOutsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = new IndexViewModel();
            model.Table = new Data[7, 7];
            var month = DateTime.Now.Month;
            var year = DateTime.Now.Year;
            var days = DateTime.DaysInMonth(year, month);

            var startDate = new DateTime(year, month, 1);
            var endDate = new DateTime(year, month, days);

            var inOuts = _context.InOuts.Where(x => x.Time >= startDate && x.Time <= endDate);

            for (int day = 1; day <= days; day++)
            {
                var date = new DateTime(year, month, day);
                var col = (int)date.DayOfWeek > 0 ? (int)date.DayOfWeek - 1 : (int)date.DayOfWeek + 6;
                var row = (day - col - 2) / 7 + 1;

                var data = new Data()
                {
                    DateString = date.ToString("dd/MM"),
                    Date = date,
                    LinkData = date.ToString("yyyy-MM-dd")
                };
                if (inOuts.FirstOrDefault(x => x.Time.Date == date.Date) != null)
                    data.HasData = true;
                else
                    data.HasData = false;

                model.Table[row, col] = data;
                model.RowMax = row;
            }

            return View(model);
        }

        public IActionResult Detail(string id)
        {
            DateTime date;
            List<DetailViewModel> model;
            try
            {
                date = DateTime.Parse(id);
                model = GetData(date.Date, date.Date);
            }
            catch
            {
                return BadRequest();
            }
            return View(model);
        }

        private List<DetailViewModel> GetData(DateTime start, DateTime end)
        {
            var stacks = new List<Stack>();
            var result = new List<DetailViewModel>();
            var data = _context.InOuts.Where(o => o.Time >= start.AddDays(-5) && o.Time <= end.AddDays(5)).OrderBy(o => o.Time).ToList();
            for (int i = 0; i < data.Count; i++)
            {
                if (data[i].Event.Contains("Vào"))
                {
                    if (stacks.FirstOrDefault(x => x.CardNumber == data[i].CardNumber) == null)
                    {
                        var stack = new Stack { CardNumber = data[i].CardNumber, Time = data[i].Time };
                        stacks.Add(stack);
                        if (result.FirstOrDefault(x => x.CardNumber == data[i].CardNumber) == null)
                        {
                            result.Add(new DetailViewModel { CardNumber = data[i].CardNumber });
                        }
                    }
                }
                else
                {
                    var stack = stacks.FirstOrDefault(x => x.CardNumber == data[i].CardNumber);
                    if (stack != null)
                    {
                        if (data[i].Time.Date >= start && data[i].Time.Date <= end)
                        {
                            var item = result.FirstOrDefault(x => x.CardNumber == data[i].CardNumber);
                            if (item != null)
                            {
                                TimeSpan diff = data[i].Time.Subtract(stack.Time);
                                item.TotalTime = item.TotalTime + diff.TotalSeconds / 60;
                            }
                        }

                        stacks.Remove(stack);
                    }
                }
            }

            return result.Where(x => x.TotalTime != 0).ToList();
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(FileUpload file)
        {
            if (_context.InOuts.FirstOrDefault(x => x.Time.Date == file.UploadDate) != null)
            {
                ModelState.AddModelError("", "Ngày đã chọn đã có dữ liệu trên hệ thống, không thể upload thêm dữ liệu");
                return View(file);
            }
            DataSet result;
            bool hasData = false;
            var fileName = Guid.NewGuid().ToString();
            var filePath = $"{Directory.GetCurrentDirectory()}\\UploadData\\{fileName}.xls";

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.FormFile.CopyToAsync(stream);
            }

            using (var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    do
                    {
                        while (reader.Read())
                        {
                        }
                    } while (reader.NextResult());

                    result = reader.AsDataSet();
                }

            }

            foreach (DataRow line in result.Tables[0].Rows)
            {
                var item = new InOut();
                try
                {
                    item.Time = DateTime.Parse(line.ItemArray[0].ToString());
                    if (item.Time.Date == file.UploadDate)
                    {
                        item.Id = Guid.NewGuid();
                        item.CardNumber = line.ItemArray[1].ToString();
                        item.Event = line.ItemArray[2].ToString();
                        item.Status = line.ItemArray[3].ToString();
                        item.Description = line.ItemArray[4].ToString();

                        hasData = true;
                        _context.InOuts.Add(item);
                    }
                }
                catch { }
            }

            if (hasData)
            {
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "File upload không chứa dữ liệu của ngày lựa chọn!");
                return View(file);
            }
        }
    }

    public class DetailViewModel
    {
        public string CardNumber { get; set; }
        public double TotalTime { get; set; } = 0;
    }

    public class Stack
    {
        public string CardNumber { get; set; }
        public DateTime Time { get; set; }
    }

    public class FileUpload
    {
        [Required]
        [Display(Name = "Ngày upload dữ liệu")]
        public DateTime UploadDate { get; set; }

        [Required]
        [Display(Name = "Chọn tệp tin dữ liệu")]
        public IFormFile FormFile { get; set; }
    }

    public class Data
    {
        public string DateString { get; set; }
        public bool HasData { get; set; }
        public string LinkData { get; set; }
        public DateTime Date { get; set; }
    }

    public class IndexViewModel
    {
        public Data[,] Table { get; set; }
        public int RowMax { get; set; } = 0;
    }
}

LaborReport/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LaborReport/Views/InOuts/Detail.cshtml
@model IEnumerable<LaborReport.Controllers.DetailViewModel>
@{
    ViewData["Title"] = "Detail";
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã thẻ</th>
            <th>Số phút</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.CardNumber</td>
                <td>@item.TotalTime.ToString("0.00")</td>
            </tr>
        }
    </tbody>
</table>

LaborReport/Views/InOuts/Index.cshtml
@model LaborReport.Controllers.IndexViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="col-6">
    <table class="table font-weight-bold">
        <thead>
            <tr>
                <th>Hai</th>
                <th>Ba</th>
                <th>Tư</th>
                <th>Năm</th>
                <th>Sáu</th>
                <th>Bảy</th>
                <th>CN</th>
            </tr>
        </thead>
        <tbody>
            @for (int row = 0; row <= Model.RowMax; row++)
            {
                <tr>
                    @for (int col = 0; col < 7; col++)
                    {
                        if (Model.Table[row, col] != null)
                        {
                            if (Model.Table[row, col].HasData)
                            {
                                <td class="bg-success"><a asp-action="Detail" asp-route-id="@Model.Table[row, col].LinkData">@Model.Table[row, col].DateString</a></td>
                            }
                            else
                            {
                                if (DateTime.Now.Date > Model.Table[row, col].Date)
                                {
                                    <td class="bg-warning">@Model.Table[row, col].DateString</td>
                                }
                                else
                                {
                                    <td>@Model.Table[row, col].DateString</td>
                                }
                            }
                        }
                        else
                        {
                            <td></td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

LaborReport/Views/InOuts/Upload.cshtml
@model LaborReport.Controllers.FileUpload
@{
    ViewData["Title"] = "Upload Data";
}

<h3>@ViewData["Title"]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UploadDate" class="control-label"></label>
                <input type="date" asp-for="UploadDate" class="form-control" />
                <span asp-validation-for="UploadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormFile" class="control-label"></label>
                <input type="file" asp-for="FormFile" class="form-control-file" accept="application/vnd.ms-excel" />
                <span asp-validation-for="FormFile" class="text-danger"></span>
            </div>
            <input type="submit" value="Upload" class="btn btn-primary btn-sm" />
        </form>
    </div>
</div>

LaborReport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container align-items-end">
                <a class="navbar-brand" href="#">
                    <img alt="Ecoba's Logo" src="~/img/logo.png" style="height:40px;" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ml-auto">
                    <ul class="navbar-nav flex-grow-1 align-items-end">
                        <li class="nav-item ml-2">
                            <a class="nav-link text-white text-uppercase" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> Home
                            </a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link text-white text-uppercase" asp-area="" asp-controller="InOuts" asp-action="Index">
                                <i class="fas fa-tachometer-alt"></i> Dashboard
                            </a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link text-white text-uppercase" asp-area="" asp-controller="InOuts" asp-action="Upload">
                                <i class="fas fa-cloud-upload-alt"></i> Upload Data
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container small">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container small">
            <div class="row flex-row">
                <div class="flex-grow-1">&copy; 2020 - Phòng phát triển và kiểm soát hệ thống</div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/logout.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>